version: "3.8"

services:
  prosody_server:
    container_name: spade_prosody_server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5347:5347"
